
/*
 * Copyright (c) 2026 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

/* Initialize one peripheral pin group. */
void Usb_Init(void);
void Uart0_Init(void);
void Mcan0_Init(void);
void Jtag_Init(void);
void Esc_P0_Init(void);
void Esc_P1_Init(void);
void Esc_Management_Init(void);
void Qei1_Init(void);
void Spi1_Init(void);
void Pwm_Init(void);
void Adc_Init(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
